---
rules:

- name: close_issues_older_than_5_minutes
  rule: close_outdated_issues
  options:
    older_than: PT2M
    apply_label: inactive
    add_comment: |
      Sorry, closing the issue as its older than 5 minutes

- name: close_outdated_prs_older_than_20_days
  rule: close_outdated_pr
  options: 
    older_than: PT2M
    apply_label: inactive
    add_comment: |
      Sorry, closing the pr as its older than 20 days

- name: pr_matches_format
  rule: pr_format
  options:
    match_title: "^#\\d+"
    apply_label: invalid
    add_comment: |
      Sorry, PRs must follow conventions:
      1. Title must start with ticket number - #123 ...
